---
version: '3.6'
services:
  prometheus:
    image: prom/prometheus:v2.43.0
    network_mode: "host"
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss:8.5.22
    network_mode: "host"
    ports:
      - 3000:3000
