{
 "title": "My Service",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Server Health (Python + Go)",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "my_server_py_health" },
    { "expr": "my_server_go_health" }
   ]
  },
  {
   "title": "CPU load (Python)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "my_server_py_cpu_load" }
   ]
  },
  {
   "title": "CPU load (Go)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    { "expr": "my_server_go_cpu_load" }
   ]
  },
  {
   "title": "Memory Usage (Python)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "my_server_py_memory_bytes_total"
    },
    { "expr": "my_server_py_memory_bytes_used" }
   ]
  },
  {
   "title": "Memory Usage (Go)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "my_server_go_memory_bytes_total"
    },
    { "expr": "my_server_go_memory_bytes_used" }
   ]
  }
 ]
}