---
global:
  scrape_interval: 15s

scrape_configs:
  # python collector
  - job_name: my_server_py
    metrics_path: /
    static_configs:
      - targets:
          - "127.0.0.1:9000"

  # go collector
  - job_name: my_server_go
    metrics_path: /
    static_configs:
      - targets:
          - "127.0.0.1:9001"

  # instrumented server
  - job_name: my_server_instr
    metrics_path: /metrics
    static_configs:
      - targets:
          - "127.0.0.1:8443"
